#!/bin/sh

./gradlew build shadowJar --build-cache

# pip3 install advent-of-code-data

for i in $(seq 31 $END); do
  FILE="inputs/2022/day$i.txt"
  if test -f "$FILE"; then
      continue
  fi
  currentDay=$(date +'%_d')
  if [ "$i" -le "$currentDay" ]; then
     aocd $i 2022 > $FILE
  fi
done

java -Xmx2g -jar -DINPUT_DIR="$(realpath inputs)" solutions/build/libs/solutions-1.0-SNAPSHOT-all.jar "$@"